config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tickets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tickets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :status, presence: true, uniqueness: true
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def index
    @tickets = Ticket.all
  end

  def new
    @ticket = Ticket.new
  end

  def show
    @ticket = Ticket.find_by_id(params[:id])
    if @ticket.nil?
      redirect_to tickets_path, notice: "Ticket not found."
    end
  end


  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render 'edit'
    end
  end


  def destroy
    puts "Ticket with id #{@ticket.id} is being deleted"
      @ticket.destroy
    redirect_to tickets_path, notice: "Ticket was successfully destroyed."
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      redirect_to @ticket
    else
      render 'new'
    end
  end

  private
  def ticket_params
    params.require(:ticket).permit(:title, :description, :status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Ticketing System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Tickets", tickets_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery_ujs' %>


    <%= javascript_importmap_tags %>
  </head>

  <body>
<%= render 'layouts/navbar' %>

    <%= yield %>

  </body>
</html>

app/views/tickets/_ticket.html.erb
<div class="ticket">
  <h2><%= ticket.title %></h2>
  <p><%= ticket.description %></p>
  <p>Status: <%= ticket.status %></p>
</div>

app/views/tickets/edit.html.erb
<div class="container mt-5">
  <h1>Edit Ticket</h1>
  <%= form_with model: @ticket, local: true do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control", rows: 5 %>
    </div>
    <div class="form-group">
      <%= form.label :status %>
      <%= form.text_field :status, class: "form-control" %>
    </div>
    <%= form.submit "Update Ticket", class: "btn btn-success btn-outline btn-lg" %>
  <% end %>
</div>

app/views/tickets/index.html.erb
<div class="container mt-5">
    <%= link_to "Create Ticket", new_ticket_path, class: "btn btn-success btn-outline btn-lg float-right" %>
  <h1>Tickets</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= ticket.title %></td>
          <td><%= ticket.description %></td>
          <td><%= ticket.status %></td>
          <td>
            <%= link_to "Show", ticket, class: "btn btn-primary btn-sm float-left" %>
            <%= link_to "Edit", edit_ticket_path(ticket), class: "btn btn-warning btn-sm float-left" %>
            <%= link_to 'Delete', ticket_path(ticket), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm float-right" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/tickets/new.html.erb
<div class="container mt-5">

<!--#### why it is not producing????###-->
  <% if @ticket.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @ticket do |form| %>
    <!-- form inputs -->
  <% end %>

  <h1>New Ticket</h1>
  <%= form_with model: @ticket, local: true do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control", rows: 5 %>
    </div>
    <div class="form-group">
      <%= form.label :status %>
      <%= form.text_field :status, class: "form-control" %>
    </div>
    <%= form.submit "Submit", class: "btn btn-success btn-outline btn-lg" %>
  <% end %>
</div>

app/views/tickets/show.html.erb
<div class="container mt-5">
  <h1>Ticket Details</h1>
  <table class="table table-bordered">
    <tr>
      <th>Title</th>
      <td><%= @ticket.title %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @ticket.description %></td>
    </tr>
    <tr>
      <th>Status</th>
      <td><%= @ticket.status %></td>
    </tr>
  </table>
  <%= link_to "Edit", edit_ticket_path(@ticket), class: "btn btn-warning mt-3 float-right" %>
  <%= link_to "Back", tickets_path, class: "btn btn-primary mt-3 float-right" %>
</div>